project:
  type: website

website:
  title: "Dhruthi Mandavilli"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: dhudhu copy.qmd
        text: About
      - href: example.qmd
        text: Example Analysis

format:
  html:
    theme: dracula
    css: styles.css
    toc: true
